### ISSUE TITLE
About the performance in RE-Docred in ATLOP

### ISSUE THREAD

**Issue by LawsonAbs** [tonytan48/Re-DocRED#2]
I run the atlop source code on re-docred. The configuration is : 
bert-base-uncased + Re_docred
Sadly, I can't get the good performance. The several epoch in our experiments is as follows
![image](https://user-images.githubusercontent.com/35190068/200174417-5ad60487-04ae-4d00-acf6-8bc36eb0e4d5.png)
what should I do?

**Comment by tonytan48** [comment]
Hi @LawsonAbs, I think ATLOP-BERT-base should be able to get 72-73 F1 performance. The scores are too long on your screenshot. Perhaps you can check the precision/recall on the reported score. If 34 F1 is due to high precision and low recall, maybe you used the original DocRED data for training and Re-DocRED for evaluation.

**Comment by LawsonAbs** [comment]
Thank you for your reply. I have solved this problem, because I ignored the setting in  official_evaluate.
